In [19]:
import numpy as np

In [20]:
matrix1=np.array([[1,2,3],[4,5,6]])

In [21]:
matrix2=np.array([[2,3,4],[3,2,4],[1,2,3]])

In [22]:
print(matrix1)

[[1 2 3]
 [4 5 6]]


In [23]:
print(matrix2)

[[2 3 4]
 [3 2 4]
 [1 2 3]]


In [24]:
matrix_mult=np.dot(matrix1,matrix2)

In [26]:
print(matrix_mult)

[[11 13 21]
 [29 34 54]]


In [28]:
transpose=np.transpose(matrix_mult)

In [30]:
print(transpose)

[[11 29]
 [13 34]
 [21 54]]
